worker_processes auto;
rtmp_auto_push on;
events {}

# 1. BLOQUE RTMP: Recibe el video pesado de OBS
rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on; # Habilita la transmisión en vivo
            record off; # No grabamos el video en disco duro permanentemente
            
            # MAGIA HLS: Convierte el RTMP a pedacitos .ts y un índice .m3u8
            hls on;
            hls_path /tmp/hls;
            hls_fragment 3; # Cada pedacito de video dura 3 segundos
            hls_playlist_length 60; # El índice guarda los últimos 60 segundos
        }
    }
}

# 2. BLOQUE HTTP: Entrega el HLS a tu frontend (Next.js)
http {
    server {
        listen 80;

        location /hls {
            # Apunta a la misma carpeta donde el bloque rtmp guarda los pedacitos
            alias /tmp/hls;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            
            # CONFIGURACIÓN CORS VITAL: Si no pones esto, Next.js bloqueará el video
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, OPTIONS';
        }
    }
}